language: c
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-elisp/ppa'
    packages:
      - openssl
      - ca-certificates
      - git
      - make
      - software-properties-common
      - dbus
      - dbus-x11
      - texinfo
      - emacs-snapshot
      - anthy-el
before_script:
  - sudo update-alternatives --set emacs /usr/bin/emacs-snapshot
script:
  - which emacs
  - ls -l /usr/bin/emacs
  - export $(dbus-launch)
  - cp -r . ~/.emacs.d
  - ln -sf ~/.emacs.d/dot.emacs ~/.emacs
  - emacs-snapshot -batch --eval "(progn (setq debug-on-error t) (require 'package) (package-initialize) (package-refresh-contents))" -l dot.emacs
