name: Lint Emacs Lisp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: '30.1'
    - name: Lint init.el
      run: emacs -batch -l init.el -f batch-byte-compile init.el
